const CATEGORY_IDS = ["animals", "food", "jobs", "countries", "sports", "places", "objects"];

const WORD_CATEGORIES_BY_LANG = {
  en: {
    animals: ["Elephant", "Giraffe", "Parrot", "Crocodile", "Rabbit", "Bear", "Dolphin", "Eagle", "Hedgehog", "Zebra", "Kangaroo", "Fox", "Owl", "Whale", "Panda"],
    food: ["Pizza", "Sushi", "Tacos", "Pancake", "Meatballs", "Lasagna", "Ice Cream", "Popcorn", "Burger", "Noodles", "Sausage", "Sandwich", "Cinnamon Bun", "Salad", "Fries"],
    jobs: ["Firefighter", "Teacher", "Dentist", "Pilot", "Chef", "Police Officer", "Hairdresser", "Carpenter", "Journalist", "Electrician", "Nurse", "Librarian", "Plumber", "Baker", "Lawyer"],
    countries: ["Sweden", "Japan", "Brazil", "Egypt", "Canada", "France", "Australia", "India", "Mexico", "Norway", "Italy", "Spain", "Thailand", "Germany", "Greece"],
    sports: ["Football", "Ice Hockey", "Swimming", "Tennis", "Table Tennis", "Boxing", "Skiing", "Golf", "Volleyball", "Cycling", "Track and Field", "Climbing", "Curling", "Handball", "Badminton"],
    places: ["School", "Hospital", "Beach", "Airport", "Library", "Gym", "Restaurant", "Forest", "Swimming Pool", "Cinema", "Shopping Mall", "Church", "Train", "Zoo", "Mountain"],
    objects: ["Umbrella", "Backpack", "Glasses", "Camera", "Bicycle", "Watch", "Thermos", "Keychain", "Headphones", "Wheelbarrow", "Fire Extinguisher", "Compass", "Flashlight", "Toothbrush", "Guitar"],
  },
  sv: {
    animals: ["Elefant", "Giraff", "Papegoja", "Krokodil", "Kanin", "Björn", "Delfin", "Örn", "Igelkott", "Zebra", "Känguru", "Räv", "Uggla", "Val", "Panda"],
    food: ["Pizza", "Sushi", "Tacos", "Pannkaka", "Köttbullar", "Lasagne", "Glass", "Popcorn", "Hamburgare", "Nudlar", "Korv", "Smörgås", "Kanelbulle", "Sallad", "Pommes"],
    jobs: ["Brandman", "Lärare", "Tandläkare", "Pilot", "Kock", "Polis", "Frisör", "Snickare", "Journalist", "Elektriker", "Sjuksköterska", "Bibliotekarie", "Rörmokare", "Bagare", "Advokat"],
    countries: ["Sverige", "Japan", "Brasilien", "Egypten", "Kanada", "Frankrike", "Australien", "Indien", "Mexiko", "Norge", "Italien", "Spanien", "Thailand", "Tyskland", "Grekland"],
    sports: ["Fotboll", "Ishockey", "Simning", "Tennis", "Bordtennis", "Boxning", "Skidåkning", "Golf", "Volleyboll", "Cykling", "Friidrott", "Klättring", "Curling", "Handboll", "Badminton"],
    places: ["Skolan", "Sjukhuset", "Stranden", "Flygplatsen", "Biblioteket", "Gymmet", "Restaurangen", "Skogen", "Simhallen", "Biografen", "Köpcentrum", "Kyrkan", "Tåget", "Zoo", "Fjället"],
    objects: ["Paraply", "Ryggsäck", "Glasögon", "Kamera", "Cykel", "Klocka", "Termos", "Nyckelknippa", "Hörlurar", "Skottkärra", "Brandsläckare", "Kompass", "Ficklampa", "Tandborste", "Gitarr"],
  },
  no: {
    animals: ["Elefant", "Sjiraff", "Papegøye", "Krokodille", "Kanin", "Bjørn", "Delfin", "Ørn", "Pinnsvin", "Sebra", "Kenguru", "Rev", "Ugle", "Hval", "Panda"],
    food: ["Pizza", "Sushi", "Tacos", "Pannekake", "Kjøttboller", "Lasagne", "Iskrem", "Popkorn", "Hamburger", "Nudler", "Pølse", "Smørbrød", "Kanelbolle", "Salat", "Pommes frites"],
    jobs: ["Brannmann", "Lærer", "Tannlege", "Pilot", "Kokk", "Politi", "Frisør", "Snekker", "Journalist", "Elektriker", "Sykepleier", "Bibliotekar", "Rørlegger", "Baker", "Advokat"],
    countries: ["Sverige", "Japan", "Brasil", "Egypt", "Canada", "Frankrike", "Australia", "India", "Mexico", "Norge", "Italia", "Spania", "Thailand", "Tyskland", "Hellas"],
    sports: ["Fotball", "Ishockey", "Svømming", "Tennis", "Bordtennis", "Boksing", "Ski", "Golf", "Volleyball", "Sykling", "Friidrett", "Klatring", "Curling", "Håndball", "Badminton"],
    places: ["Skolen", "Sykehuset", "Stranden", "Flyplassen", "Biblioteket", "Treningssenteret", "Restauranten", "Skogen", "Svømmebassenget", "Kinoen", "Kjøpesenteret", "Kirken", "Toget", "Dyrehagen", "Fjellet"],
    objects: ["Paraply", "Ryggsekk", "Briller", "Kamera", "Sykkel", "Klokke", "Termos", "Nøkkelknippe", "Hodetelefoner", "Trillebår", "Brannslukningsapparat", "Kompass", "Lommelykt", "Tannbørste", "Gitar"],
  },
  da: {
    animals: ["Elefant", "Giraf", "Papegøje", "Krokodille", "Kanin", "Bjørn", "Delfin", "Ørn", "Pindsvin", "Zebra", "Kænguru", "Ræv", "Ugle", "Hval", "Panda"],
    food: ["Pizza", "Sushi", "Tacos", "Pandekage", "Frikadeller", "Lasagne", "Is", "Popcorn", "Burger", "Nudler", "Pølse", "Sandwich", "Kanelsnegl", "Salat", "Pommes frites"],
    jobs: ["Brandmand", "Lærer", "Tandlæge", "Pilot", "Kok", "Politibetjent", "Frisør", "Tømrer", "Journalist", "Elektriker", "Sygeplejerske", "Bibliotekar", "Blikkenslager", "Bager", "Advokat"],
    countries: ["Sverige", "Japan", "Brasilien", "Egypten", "Canada", "Frankrig", "Australien", "Indien", "Mexico", "Norge", "Italien", "Spanien", "Thailand", "Tyskland", "Grækenland"],
    sports: ["Fodbold", "Ishockey", "Svømning", "Tennis", "Bordtennis", "Boksning", "Skiløb", "Golf", "Volleyball", "Cykling", "Atletik", "Klatring", "Curling", "Håndbold", "Badminton"],
    places: ["Skolen", "Hospitalet", "Stranden", "Lufthavnen", "Biblioteket", "Fitnesscentret", "Restauranten", "Skoven", "Svømmehallen", "Biografen", "Indkøbscentret", "Kirken", "Toget", "Zoologisk have", "Bjerget"],
    objects: ["Paraply", "Rygsæk", "Briller", "Kamera", "Cykel", "Ur", "Termokande", "Nøglering", "Hovedtelefoner", "Trillebør", "Brandslukker", "Kompas", "Lommelygte", "Tandbørste", "Guitar"],
  },
  fi: {
    animals: ["Norsu", "Kirahvi", "Papukaija", "Krokotiili", "Kani", "Karhu", "Delfiini", "Kotka", "Siili", "Seepra", "Kenguru", "Kettu", "Pöllö", "Valas", "Panda"],
    food: ["Pizza", "Sushi", "Tacot", "Pannukakku", "Lihapullat", "Lasagne", "Jäätelö", "Popcorn", "Hampurilainen", "Nuudelit", "Makkara", "Voileipä", "Korvapuusti", "Salaatti", "Ranskalaiset"],
    jobs: ["Palomies", "Opettaja", "Hammaslääkäri", "Lentäjä", "Kokki", "Poliisi", "Kampaaja", "Puuseppä", "Toimittaja", "Sähköasentaja", "Sairaanhoitaja", "Kirjastonhoitaja", "Putkimies", "Leipuri", "Asianajaja"],
    countries: ["Ruotsi", "Japani", "Brasilia", "Egypti", "Kanada", "Ranska", "Australia", "Intia", "Meksiko", "Norja", "Italia", "Espanja", "Thaimaa", "Saksa", "Kreikka"],
    sports: ["Jalkapallo", "Jääkiekko", "Uinti", "Tennis", "Pöytätennis", "Nyrkkeily", "Hiihto", "Golf", "Lentopallo", "Pyöräily", "Yleisurheilu", "Kiipeily", "Curling", "Käsipallo", "Sulkapallo"],
    places: ["Koulu", "Sairaala", "Ranta", "Lentokenttä", "Kirjasto", "Kuntosali", "Ravintola", "Metsä", "Uimahalli", "Elokuvateatteri", "Ostoskeskus", "Kirkko", "Juna", "Eläintarha", "Vuori"],
    objects: ["Sateenvarjo", "Reppu", "Silmälasit", "Kamera", "Polkupyörä", "Kello", "Termospullo", "Avaimenperä", "Kuulokkeet", "Kottikärry", "Sammutin", "Kompassi", "Taskulamppu", "Hammasharja", "Kitara"],
  },
  fr: {
    animals: ["Éléphant", "Girafe", "Perroquet", "Crocodile", "Lapin", "Ours", "Dauphin", "Aigle", "Hérisson", "Zèbre", "Kangourou", "Renard", "Hibou", "Baleine", "Panda"],
    food: ["Pizza", "Sushi", "Tacos", "Crêpe", "Boulettes de viande", "Lasagnes", "Glace", "Pop-corn", "Hamburger", "Nouilles", "Saucisse", "Sandwich", "Pain aux raisins", "Salade", "Frites"],
    jobs: ["Pompier", "Enseignant", "Dentiste", "Pilote", "Chef cuisinier", "Policier", "Coiffeur", "Menuisier", "Journaliste", "Électricien", "Infirmier", "Bibliothécaire", "Plombier", "Boulanger", "Avocat"],
    countries: ["Suède", "Japon", "Brésil", "Égypte", "Canada", "France", "Australie", "Inde", "Mexique", "Norvège", "Italie", "Espagne", "Thaïlande", "Allemagne", "Grèce"],
    sports: ["Football", "Hockey sur glace", "Natation", "Tennis", "Tennis de table", "Boxe", "Ski", "Golf", "Volley-ball", "Cyclisme", "Athlétisme", "Escalade", "Curling", "Handball", "Badminton"],
    places: ["École", "Hôpital", "Plage", "Aéroport", "Bibliothèque", "Salle de sport", "Restaurant", "Forêt", "Piscine", "Cinéma", "Centre commercial", "Église", "Train", "Zoo", "Montagne"],
    objects: ["Parapluie", "Sac à dos", "Lunettes", "Appareil photo", "Vélo", "Montre", "Thermos", "Porte-clés", "Écouteurs", "Brouette", "Extincteur", "Boussole", "Lampe de poche", "Brosse à dents", "Guitare"],
  },
  de: {
    animals: ["Elefant", "Giraffe", "Papagei", "Krokodil", "Kaninchen", "Bär", "Delfin", "Adler", "Igel", "Zebra", "Känguru", "Fuchs", "Eule", "Wal", "Panda"],
    food: ["Pizza", "Sushi", "Tacos", "Pfannkuchen", "Frikadellen", "Lasagne", "Eis", "Popcorn", "Burger", "Nudeln", "Wurst", "Sandwich", "Zimtschnecke", "Salat", "Pommes"],
    jobs: ["Feuerwehrmann", "Lehrer", "Zahnarzt", "Pilot", "Koch", "Polizist", "Friseur", "Zimmermann", "Journalist", "Elektriker", "Krankenschwester", "Bibliothekar", "Klempner", "Bäcker", "Anwalt"],
    countries: ["Schweden", "Japan", "Brasilien", "Ägypten", "Kanada", "Frankreich", "Australien", "Indien", "Mexiko", "Norwegen", "Italien", "Spanien", "Thailand", "Deutschland", "Griechenland"],
    sports: ["Fußball", "Eishockey", "Schwimmen", "Tennis", "Tischtennis", "Boxen", "Skifahren", "Golf", "Volleyball", "Radfahren", "Leichtathletik", "Klettern", "Curling", "Handball", "Badminton"],
    places: ["Schule", "Krankenhaus", "Strand", "Flughafen", "Bibliothek", "Fitnessstudio", "Restaurant", "Wald", "Schwimmbad", "Kino", "Einkaufszentrum", "Kirche", "Zug", "Zoo", "Berg"],
    objects: ["Regenschirm", "Rucksack", "Brille", "Kamera", "Fahrrad", "Uhr", "Thermoskanne", "Schlüsselbund", "Kopfhörer", "Schubkarre", "Feuerlöscher", "Kompass", "Taschenlampe", "Zahnbürste", "Gitarre"],
  },
  es: {
    animals: ["Elefante", "Jirafa", "Loro", "Cocodrilo", "Conejo", "Oso", "Delfín", "Águila", "Erizo", "Cebra", "Canguro", "Zorro", "Búho", "Ballena", "Panda"],
    food: ["Pizza", "Sushi", "Tacos", "Panqueque", "Albóndigas", "Lasaña", "Helado", "Palomitas", "Hamburguesa", "Fideos", "Salchicha", "Sándwich", "Rollo de canela", "Ensalada", "Papas fritas"],
    jobs: ["Bombero", "Profesor", "Dentista", "Piloto", "Chef", "Policía", "Peluquero", "Carpintero", "Periodista", "Electricista", "Enfermero", "Bibliotecario", "Fontanero", "Panadero", "Abogado"],
    countries: ["Suecia", "Japón", "Brasil", "Egipto", "Canadá", "Francia", "Australia", "India", "México", "Noruega", "Italia", "España", "Tailandia", "Alemania", "Grecia"],
    sports: ["Fútbol", "Hockey sobre hielo", "Natación", "Tenis", "Tenis de mesa", "Boxeo", "Esquí", "Golf", "Voleibol", "Ciclismo", "Atletismo", "Escalada", "Curling", "Balonmano", "Bádminton"],
    places: ["Escuela", "Hospital", "Playa", "Aeropuerto", "Biblioteca", "Gimnasio", "Restaurante", "Bosque", "Piscina", "Cine", "Centro comercial", "Iglesia", "Tren", "Zoológico", "Montaña"],
    objects: ["Paraguas", "Mochila", "Gafas", "Cámara", "Bicicleta", "Reloj", "Termo", "Llavero", "Auriculares", "Carretilla", "Extintor", "Brújula", "Linterna", "Cepillo de dientes", "Guitarra"],
  },
};
